const PRODUCTS = [
{id:1,name:"Sauvage Eau de Parfum",house:"Dior",type:"designer",gender:"Men",tags:["fresh","woody"],notes:"Bergamot · Vanilla · Patchouli",tone:1,featured:true,image:"https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw24a244fd/Y0785220/Y0785220_F078524009_E01_RHC.jpg?sw=800"},
{id:3,name:"J'adore Eau de Parfum",house:"Dior",type:"designer",gender:"Women",tags:["floral"],notes:"Ylang-Ylang · Jasmine · Rose",tone:5,image:"https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwc1455521/Y0998031/Y0998031_C099800245_E01_RHC.jpg?sw=800"},
{id:22,name:"Oud Wood",house:"Tom Ford",type:"designer",gender:"Unisex",tags:["woody","amber"],notes:"Oud · Rosewood · Cardamom · Amber",tone:8,featured:true,image:"https://www.atticadps.gr/images/h2160/8/jpg/files/products/888066024082/1.jpg"},
{id:30,name:"Herod",house:"Parfums de Marly",type:"niche",gender:"Men",tags:["woody","amber"],notes:"Cinnamon · Tobacco · Vanilla · Cedar",tone:4,image:"https://www.parfuemerie-heudorf-shop.de/media/08/3d/49/1699028663/Marly%20Herod%20125ml.jpg"}
];
const SIZES={2:{label:"2ml",price:8},5:{label:"5ml",price:20},10:{label:"10ml",price:30}};
let cart=JSON.parse(localStorage.getItem("eclatCart")||"[]");
let wishlist=JSON.parse(localStorage.getItem("eclatWishlist")||"[]");
let currentFilter="all", currentGender="all", currentHouse="all", searchTerm="";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>`€${n.toFixed(0)}`;
function save(){localStorage.setItem("eclatCart",JSON.stringify(cart));localStorage.setItem("eclatWishlist",JSON.stringify(wishlist));}
function product(id){return PRODUCTS.find(p=>p.id===Number(id));}
function selectedPrice(size){return SIZES[size].price;}
function initBrandDirectory(){const brands=[...new Set(PRODUCTS.map(p=>p.house))].sort();$("#brandFilter").innerHTML='<option value="all">All brands</option>'+brands.map(b=>`<option value="${b}">${b}</option>`).join("");$("#brandDirectory").innerHTML='<button class="brand-chip active" data-brand="all">All brands</button>'+brands.map(b=>`<button class="brand-chip" data-brand="${b}">${b}</button>`).join("");$$('.brand-chip').forEach(b=>b.onclick=()=>{currentHouse=b.dataset.brand;$("#brandFilter").value=currentHouse;$$('.brand-chip').forEach(x=>x.classList.toggle('active',x===b));renderProducts();document.querySelector('#productGrid').scrollIntoView({behavior:'smooth',block:'start'});});}
function renderProducts(){let list=PRODUCTS.filter(p=>{const filterOk=currentFilter==="all"||p.type===currentFilter||p.tags.includes(currentFilter);const genderOk=currentGender==="all"||p.gender===currentGender;const houseOk=currentHouse==="all"||p.house===currentHouse;const q=searchTerm.toLowerCase();const searchOk=!q||[p.name,p.house,p.type,p.gender,p.notes,...p.tags].join(" ").toLowerCase().includes(q);return filterOk&&genderOk&&houseOk&&searchOk;});const sort=$("#sortSelect").value;if(sort==="name")list.sort((a,b)=>a.name.localeCompare(b.name));if(sort==="brand")list.sort((a,b)=>a.house.localeCompare(b.house)||a.name.localeCompare(b.name));if(sort==="featured")list.sort((a,b)=>Number(b.featured)-Number(a.featured)||a.house.localeCompare(b.house));$("#resultsCount").textContent=`${list.length} fragrance${list.length===1?"":"s"}`;$("#productGrid").innerHTML=list.length?list.map(cardHTML).join(""):`<div class="no-results"><h3>No scents found.</h3><p>Try another search or reset the filters.</p><button class="btn btn-dark" onclick="resetFilters()">Reset filters</button></div>`;$$('.add-btn').forEach(b=>b.onclick=()=>addToCart(b.dataset.id,b.parentElement.querySelector('.size-select').value));$$('.quick-btn').forEach(b=>b.onclick=()=>openQuick(b.dataset.id));$$('.wish').forEach(b=>b.onclick=()=>toggleWish(b.dataset.id));}
function cardHTML(p){const wished=wishlist.includes(p.id);const visual=p.image?`<img class="product-image" src="${p.image}" alt="${p.house} ${p.name} perfume bottle" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`:`<div class="photo-fallback"><strong>${p.house}</strong><span>${p.name}</span></div>`;return `<article class="product-card"><div class="product-visual tone-${p.tone}" onclick="openQuick(${p.id})">${p.featured?'<span class="badge">Featured</span>':''}<button class="wish ${wished?'active':''}" data-id="${p.id}" aria-label="Wishlist">${wished?'♥':'♡'}</button>${visual}</div><div class="product-info"><div class="product-top"><div><h3 class="product-name">${p.name}</h3><p class="product-house">${p.house} · ${p.gender}</p></div><span class="product-price">from €8</span></div><p class="notes">${p.notes}</p><div class="product-actions"><select class="size-select" aria-label="Choose size">${Object.entries(SIZES).map(([k,v])=>`<option value="${k}">${v.label} · ${money(v.price)}</option>`).join("")}</select><button class="btn btn-dark add-btn" data-id="${p.id}">Add</button><button class="quick-btn" data-id="${p.id}" aria-label="Quick view">+</button></div></div></article>`;}
function toggleWish(id){id=Number(id);wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save();renderProducts();$("#wishlistCount").textContent=wishlist.length;toast(wishlist.includes(id)?"Added to wishlist":"Removed from wishlist")}
function addToCart(id,size){id=Number(id);size=Number(size);const key=`${id}-${size}`;const existing=cart.find(x=>x.key===key);if(existing)existing.qty++;else cart.push({key,id,size,qty:1});save();renderCart();openCart();toast("Added to your bag")}
function changeQty(key,delta){const item=cart.find(x=>x.key===key);if(!item)return;item.qty+=delta;if(item.qty<=0)cart=cart.filter(x=>x.key!==key);save();renderCart()}
function removeItem(key){cart=cart.filter(x=>x.key!==key);save();renderCart();toast("Removed from your bag")}
function cartTotal(){return cart.reduce((sum,x)=>sum+selectedPrice(x.size)*x.qty,0)}
function renderCart(){const total=cartTotal(),count=cart.reduce((s,x)=>s+x.qty,0);$("#cartCount").textContent=count;$("#cartSubtotal").textContent=money(total);$("#shippingNote").textContent=total>=75?"Complimentary shipping unlocked.":"Shipping calculated at checkout.";$("#cartItems").innerHTML=cart.map(x=>{const p=product(x.id);return `<div class="cart-row"><div class="cart-thumb tone-${p.tone}">${p.image?`<img class="cart-product-image" src="${p.image}" alt="${p.name}" loading="lazy">`:''}</div><div><h4>${p.name}</h4><small>${p.house} · ${SIZES[x.size].label}</small><div class="qty"><button onclick="changeQty('${x.key}',-1)">−</button><span>${x.qty}</span><button onclick="changeQty('${x.key}',1)">+</button></div><button class="remove" onclick="removeItem('${x.key}')">Remove</button></div><strong>${money(selectedPrice(x.size)*x.qty)}</strong></div>`}).join("");const empty=!cart.length;$("#emptyCart").style.display=empty?"block":"none";$("#cartItems").style.display=empty?"none":"block";$("#cartFooter").style.display=empty?"none":"block"}
function openCart(){$("#cartDrawer").classList.add("open");$("#cartDrawer").setAttribute("aria-hidden","false");$("#overlay").classList.add("show")}
function closeCart(){$("#cartDrawer").classList.remove("open");$("#cartDrawer").setAttribute("aria-hidden","true");$("#overlay").classList.remove("show")}
function openQuick(id){const p=product(id);$("#quickContent").innerHTML=`<div class="quick-layout"><div class="quick-visual tone-${p.tone}">${p.image?`<img class="quick-product-image" src="${p.image}" alt="${p.house} ${p.name}">`:`<div class="photo-fallback large"><strong>${p.house}</strong><span>${p.name}</span></div>`}</div><div class="quick-copy"><p class="eyebrow">${p.type} · ${p.house} · ${p.gender}</p><h2>${p.name}</h2><p>${p.notes}</p><p>Choose a discovery size and add it to your bag.</p><div class="quick-price">From €8</div><div class="product-actions"><select id="quickSize" class="size-select">${Object.entries(SIZES).map(([k,v])=>`<option value="${k}">${v.label} · ${money(v.price)}</option>`).join("")}</select><button class="btn btn-dark" id="quickAdd">Add to bag</button></div></div></div>`;$("#quickAdd").onclick=()=>{addToCart(id,$("#quickSize").value);closeModal("quickModal")};$("#quickModal").classList.add("open")}
function closeModal(id){$("#"+id).classList.remove("open")}
function resetFilters(){currentFilter="all";currentGender="all";currentHouse="all";searchTerm="";$("#searchInput").value="";$("#brandFilter").value="all";$("#genderFilter").value="all";$$('.filter').forEach(b=>b.classList.toggle("active",b.dataset.filter==="all"));renderProducts()}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove("show"),1800)}
function checkout(){if(!cart.length){toast("Your bag is empty");return}const lines=cart.map(x=>{const p=product(x.id);return `${x.qty} × ${p.name} (${SIZES[x.size].label}) — ${money(selectedPrice(x.size))}`}).join("<br>");$("#checkoutSummary").innerHTML=`${lines}<hr><strong>Total: ${money(cartTotal())}</strong>`;$("#checkoutTotal").textContent=money(cartTotal());closeCart();$("#checkoutModal").classList.add("open")}
const cartBtn=$("#cartBtn"); if (cartBtn) cartBtn.onclick=openCart;
const closeCartBtn=$("#closeCart"); if (closeCartBtn) closeCartBtn.onclick=closeCart;
const overlay=$("#overlay"); if (overlay) overlay.onclick=closeCart;
const continueBtn=$("#continueBtn"); if (continueBtn) continueBtn.onclick=closeCart;
const emptyShop=$("#emptyShop"); if (emptyShop) emptyShop.onclick=closeCart;
const checkoutBtn=$("#checkoutBtn"); if (checkoutBtn) checkoutBtn.onclick=checkout;
const searchToggle=$("#searchToggle"); if (searchToggle) searchToggle.onclick=()=>{$("#searchPanel").classList.toggle("open");if($("#searchPanel").classList.contains("open"))$("#searchInput").focus()};
const clearSearch=$("#clearSearch"); if (clearSearch) clearSearch.onclick=()=>{$("#searchInput").value="";searchTerm="";renderProducts()};
const searchInput=$("#searchInput"); if (searchInput) searchInput.oninput=e=>{searchTerm=e.target.value;renderProducts()};
const sortSelect=$("#sortSelect"); if (sortSelect) sortSelect.onchange=renderProducts;
$$('.filter').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts()});
const brandFilter=$("#brandFilter"); if (brandFilter) brandFilter.onchange=e=>{currentHouse=e.target.value;renderProducts()};
const genderFilter=$("#genderFilter"); if (genderFilter) genderFilter.onchange=e=>{currentGender=e.target.value;renderProducts()};
$$('.collection-card').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===currentFilter));document.querySelector('#shop').scrollIntoView({behavior:'smooth'});renderProducts()});
const resetFiltersBtn=$("#resetFilters"); if (resetFiltersBtn) resetFiltersBtn.onclick=resetFilters;
const wishlistBtn=$("#wishlistBtn"); if (wishlistBtn) wishlistBtn.onclick=()=>{if(!wishlist.length){toast("Your wishlist is empty");return}searchTerm="";currentFilter="all";currentGender="all";currentHouse="all";$("#searchInput").value="";$("#resultsCount").textContent=`${wishlist.length} wishlisted`;$("#productGrid").innerHTML=PRODUCTS.filter(p=>wishlist.includes(p.id)).map(cardHTML).join("");$$('.add-btn').forEach(b=>b.onclick=()=>addToCart(b.dataset.id,b.parentElement.querySelector('.size-select').value));$$('.quick-btn').forEach(b=>b.onclick=()=>openQuick(b.dataset.id));$$('.wish').forEach(b=>b.onclick=()=>toggleWish(b.dataset.id))};
const menuBtn=$("#menuBtn"); if (menuBtn) menuBtn.onclick=()=>{const mainNav=$("#mainNav");if(mainNav)mainNav.classList.toggle('open')};
$$('.modal-close').forEach(b=>b.onclick=()=>{const modal=b.closest('.modal');if(modal)modal.classList.remove('open')});
const checkoutForm=$("#checkoutForm"); if (checkoutForm) checkoutForm.onsubmit=e=>{e.preventDefault();cart=[];save();renderCart();$("#checkoutModal").classList.remove('open');$("#successModal").classList.add('open')};
const successClose=$("#successClose"); if (successClose) successClose.onclick=()=>{$("#successModal").classList.remove('open');location.hash='#shop'};
const newsletterForm=$("#newsletterForm"); if (newsletterForm) newsletterForm.onsubmit=e=>{e.preventDefault();$("#newsletterMessage").textContent="You're on the list — welcome to the Scent Letter.";$("#newsletterEmail").value="";toast("Welcome to the Scent Letter")};
$$('[data-modal]').forEach(a=>a.onclick=e=>{e.preventDefault();toast(`${a.dataset.modal==='shipping'?'Shipping':'Privacy'} information can be connected to your final store policy.`)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();$$('.modal').forEach(m=>m.classList.remove('open'))}});
initBrandDirectory();renderProducts();renderCart();$("#wishlistCount").textContent=wishlist.length;